en-US/intro/roadmap.md
Removed the word "we" - it did not occur in the other bullet points, so shouldn't be here either.
=> Updated roadmap.md

en-US/advanced/configuration_cheat_sheet.md
=> add SKIP_VERIFY option

en-US/advanced/configuration_cheat_sheet.md
=> Fixes spelling mistake

fr-FR/about.md, fr-FR/advanced/README.md, fr-FR/advanced/configuration_cheat_sheet.md, fr-FR/advanced/configuration_for_source_builds.md, fr-FR/advanced/hacking_on_gogs.md, fr-FR/advanced/release_and_tips_blogs.md, fr-FR/donate.md, fr-FR/features/README.md, fr-FR/features/authentication.md, fr-FR/features/i18n.md, fr-FR/features/migrate.md, fr-FR/features/webhook.md, fr-FR/installation/README.md, fr-FR/installation/configuration_and_run.md, fr-FR/installation/install_from_binary.md, fr-FR/installation/install_from_packages.md, fr-FR/installation/install_from_source.md, fr-FR/installation/install_gogs_on_mac.md, fr-FR/installation/install_gogs_on_windows.md, fr-FR/intro/README.md, fr-FR/intro/change_log.md, fr-FR/intro/faqs.md, fr-FR/intro/known_issues.md, fr-FR/intro/troubleshooting.md, fr-FR/team.md
first translation in french, bonjour :)
=> Translate docs Gogs in french

en-US/advanced/configuration_cheat_sheet.md
Hi all. I just installed Gogs today and it's great! The language in the EN docs reads a little non-native to me (presuming here, forgive me), so I thought I'd touch it up a bit. I hope it's helpful and welcome. I just started with the one page for now, but could do some more if it's useful.
Thanks!
=> grammar and punctuation tweaks to config cheat sheet

en-US/installation/install_from_packages.md, fr-FR/installation/install_from_packages.md, zh-CN/installation/install_from_packages.md
So, no update is needed after a new release.
=> Removed release version out of doc

en-US/intro/faqs.md
Not sure if this fits in the documentation, but it is something I had to do to get my repos to work.
Might help others setting up for the first time.
=> Added - Possible helpful hint

en-US/installation/README.md, en-US/installation/configuration_and_run.md, en-US/installation/install_from_binary.md, en-US/installation/install_from_packages.md, en-US/installation/install_from_source.md, en-US/installation/install_gogs_on_mac.md, en-US/installation/install_gogs_on_windows.md
Hi again! I hope this PR isn't too hefty. I've gone through the installation section of the docs and fixed some formatting, a few spelling errors, and some grammatical roughness.
Thanks!
=> Formatting, grammar, spelling updates for Installation section docs

fr-FR/intro/README.md
Improving the understandability of the project's description
=> README Update | FR

en-US/installation/install_gogs_on_windows.md
=> en-US/installation: update to run directly as a windows service

en-US/upgrade/upgrade_from_source.md
On old information talk to remove folder, but isn't, is only to update, If remove, will lose actual configuration
=> Small fix on upgrade information

en-US/intro/faqs.md
the default port is 3000 not 6000 and / need to be added at the end of the line
added a rememinder to http-proxy mod
=> fixed apache config

de-DE/advanced/configuration_cheat_sheet.md, de-DE/advanced/configuration_for_source_builds.md, de-DE/advanced/hacking_on_gogs.md, de-DE/features/authentication.md, de-DE/installation/README.md, de-DE/installation/configuration_and_run.md, de-DE/installation/install_from_source.md, de-DE/installation/install_gogs_on_windows.md, de-DE/intro/faqs.md, de-DE/intro/troubleshooting.md
Fixes #97 and contains many other improvements of the German translation.
=> Fix typos in de-DE

fr-FR/intro/faqs.md
I have correct some small errors in your translation.
=> Update french translation of faq.md

en-US/advanced/configuration_for_source_builds.md
We are gong to setup Gogs -> We are going to setup Gogs
=> Small typo

en-US/advanced/configuration_for_source_builds.md
We are gong to setup Gogs along with **Nginx**.
should be 
We are going to setup Gogs along with **Nginx**.
=> Fix typo in configuration_for_source_builds.md

en-US/advanced/configuration_cheat_sheet.md
the setting is available since v0.9.71
=> Add picture.ENABLE_FEDERATED_AVATAR docs

de-DE/intro/faqs.md, en-US/intro/faqs.md
Added Apache 2 proxy configuration example, english and german.
See [Mageti's comment](https://github.com/gogits/gogs/issues/806#issuecomment-68353194).
Corrected Apache 2 proxy example for sub-url (trailing slash has to be omitted).
See [gogs#1202](https://github.com/gogits/gogs/issues/1202), [Running app on subdir. HTTP 404 error](https://discuss.gogs.io/t/running-app-on-subdir-http-404-error/527) and [Yet another way to work with Apache2 proxy](https://discuss.gogs.io/t/yet-another-way-to-work-with-apache2-proxy/25).
=> Improved documentation for Apache 2 proxy configuration (en/ger).

de-DE/advanced/configuration_for_source_builds.md
While following the docs i found these 2 typos in the instruction.
=> fixed 2 typos

en-US/advanced/configuration_cheat_sheet.md
Update docs to put it in line with gogits/gogs#2947
=> Mysql is not a session provider

de-DE/advanced/configuration_cheat_sheet.md, en-US/advanced/configuration_cheat_sheet.md
=> Added [other] SHOW_FOOTER_TEMPLATE_LOAD_TIME

en-US/features/webhook.md
A lot has changed in the hook data ... this update is sorely needed!
=> Updated hook data

fr-FR/advanced/configuration_cheat_sheet.md, fr-FR/advanced/configuration_for_source_builds.md, fr-FR/advanced/hacking_on_gogs.md, fr-FR/features/custom_template.md, fr-FR/features/i18n.md, fr-FR/features/webhook.md, fr-FR/installation/configuration_and_run.md, fr-FR/installation/install_from_packages.md, fr-FR/installation/install_from_source.md, fr-FR/intro/faqs.md, fr-FR/intro/troubleshooting.md
I did a first pass on the french translation in the current state.
A lot of sentences were incorrect, not even french sometimes. I tried my best to correct them. I think at least it's now readable and understandable.
=> Update the french translation

de-DE/installation/install_from_packages.md, en-US/installation/install_from_packages.md, fr-FR/installation/install_from_packages.md
=> Add link to Synology package

fr-FR/advanced/configuration_cheat_sheet.md
Removed TASK_INTERVAL no existant option
Add PAGING_NUM missing option
=> configuration cheat sheet [webhook]

de-DE/installation/install_from_packages.md, en-US/installation/install_from_packages.md, zh-CN/installation/install_from_packages.md
See particular commit messages.
=> Update links for Arch packages

en-US/intro/faqs.md
- Re-arrange word order in notes about the `/` suffixes
- Add _the_ to sentences where it's missing
- _on_ an intranet vs _in_ an intranet
=> Improve grammar in FAQs document

de-DE/intro/faqs.md, en-US/intro/faqs.md, fr-FR/intro/faqs.md, zh-CN/intro/faqs.md
doc: update lighttpd config
github: fixes #161
github: fixes https://github.com/gogits/gogs/issues/4741
=> doc: update lighttpd config

fr-FR/intro/troubleshooting.md
In French typography a ":" is followed by a lowercase.
=> Put lowercases in french documentation when needed

en-US/features/custome_template.md
Clarify process of overriding templates vs simple code injection.
=> Update docs on how to use custom templates

en-US/advanced/configuration_cheat_sheet.md
Document allowed values: unix and fcgi.
=> Add more protocols

en-US/intro/faqs.md
No changes other than a link from the main FAQ
=> link to openrc daemon section (Gentoo, Funtoo)

en-US/upgrade/upgrade_from_binary.md
The previous filename is not found.
=> Fix filename

en-US/installation/install_from_binary.md, zh-CN/installation/install_from_binary.md
I misunderstood the words "Go to /install to do your first-time run configuration". I thought it was "Go to $GOGS_HOME/install to find something useful". Sure there is no such directory.
Need double check if I still misunderstand something.
=> Better installation guides

fr-FR/installation/configuration_and_run.md
added a "e" at the end of a word to better respect french grammar
=> Fixed typo in a title
