- en-US/installation/install_gogs_on_mac.md
Fix a spelling mistake in the Mac OS X installation guide.
> Fix spelling mistake

- en-US/installation/install_from_source.md
- fr-FR/installation/install_from_source.md
- zh-CN/installation/install_from_source.md
When you clone the code to install from source it is not necessary to download the full history of the branch. The last revision is enough.
This saves disk space, bandwith and time.
> get only last revision when cloning source

- en-US/installation/install_from_source.md
{GOOS_GOARCH} => ${GOOS}_${GOARCH}
> typo correction

- TOC.ini
- en-US/upgrade/README.md
- en-US/upgrade/upgrade_from_source.md
This is a simple way to upgrade Gogs from source if you already have Gogs running.
> Include documentation to upgrade Gogs from source

- en-US/advanced/configuration_cheat_sheet.md
Previous formatting did not show the `<>`, therefore causing a misconfiguration on my side (until I read RFC 5322).
Hope this helps anyone else, too!
A related link:
http://stackoverflow.com/questions/22433687/how-to-format-an-email-that-hotmail-outlook-is-happy-with
> Updated to minimize confusion

- en-US/features/authentication.md
1. "Username attribute" is an attribute, not search filter. Fix description
accordingly.
2. Replace "user's username" with "login name given on sign-in form", since the
%s replacement does not essentially needs to be user's username, it can be
anything (eg. email or even phone number), as long LDAP query using the
replacement matches some record.
> LDAP: Fix username attribute description

- en-US/advanced/hacking_on_gogs.md
Also, Gogs have 3 different pages with information about how to contribute:
- https://github.com/gogits/gogs/blob/master/CONTRIBUTING.md
- https://github.com/gogits/gogs/wiki/Contributing-Code
- https://gogs.io/docs/advanced/hacking_on_gogs
And they aren't in sync! (Not all information is available on all pages). I think it would be better to consolidate these pages in a single one (making sure it is easily findable).
Just a suggestion.
> Updating "Hacking on Gogs"

- de-DE/installation/configuration_and_run.md
Just noticed a small typo in the german translation.
> Fix typo in bra source URL

- en-US/advanced/hacking_on_gogs.md
The 'go get' command already makes a clone of the gogs repository which can then be configure to point at the user's fork without having to re-download the entire repository again.
> Update the git remote instead of re-cloning the gogs repo

- en-US/intro/troubleshooting.md
I corrected a simple typo on the docs: Storate > Storage
> Correct typo

- de-DE/advanced/configuration_cheat_sheet.md
- en-US/advanced/configuration_cheat_sheet.md
- fr-FR/advanced/configuration_cheat_sheet.md
As mentioned in [issue 264](https://github.com/gogits/gogs/issues/264) of the gogs main repo, gogs contains a dedicated setting to allow the execution of git hooks which wasn't reflected in the documentation until now.
> Added ENABLE_GIT_HOOKS setting to cheat sheet

- en-US/installation/install_from_source.md
If this happens
go build error : `fatal error: security/pam_appl.h: No such file or directory`
then install missing package
`sudo apt-get install libpam0g-dev` # debian, ubuntu
`sudo yum install gcc pam-devel `  #  On CentOS, Fedora or RHEL
> added mention of missing package to fix gobuild error

- en-US/intro/faqs.md
I have added sections to configure [Caddy](https://caddyserver.com/) (a webserver written in GO)  as a proxy to point to a Gogs instance.
> Add sections for proxy with Caddy

- en-US/advanced/hacking_on_gogs.md
The reference for the official testing documentation was setup incorrectly, leading to a 404.
Inlining the reference for this link seems to be the way these are handled elsewhere in the docs.
> Fix broken link in hacking_on_gogs.md

- en-US/upgrade/upgrade_from_binary.md
During a recent upgrade (https://dl.gogs.io/0.10.18/linux_amd64.tar.gz), my init.d script stopped working because the bundled script didn't have the execute bit set. 
```
$ sudo service gogs start
gogs: unrecognized service
$ ls -l /etc/init.d/gogs
lrwxrwxrwx 1 root root 39 Oct 10 10:07 /etc/init.d/gogs -> /home/git/gogs/scripts/init/debian/gogs
$ ls -l /home/git/gogs/scripts/init/debian/gogs
-rw-r--r-- 1 git git 3112 Feb 21 09:44 /home/git/gogs/scripts/init/debian/gogs
$ sudo chmod +x /home/git/gogs/scripts/init/debian/gogs
$ sudo service gogs start
* Starting Gogs gogs                                                                                                           [ OK ]
```
I suppose this might be better fixed in the packaging scripts in the main gogs repo, but I didn't feel …
> Update to upgrade-from-binary steps

- en-US/features/authentication.md
Heading does not display correctly here: https://gogs.io/docs/features/authentication
> Fix FreeIPA heading in Authentication docs

- en-US/advanced/configuration_cheat_sheet.md
In certain contexts, the Gogs configuration is put together by concatenating multiple files. In such a situation, it becomes hard to override the values in the Overall section as they get pushed into whatever section is defined last, unless you know that it can be specified via `DEFAULT`.
> document the section name for "Overall" section

- zh-CN/installation/run_as_windows_service.md
> fixed sc create command

- en-US/intro/faqs.md
Add descriptions of the simple way to reset forgotten administrator password
using shell access to server and command line interface.
There's no need to use low-level "SQL magic" or any other dirty tricks to do this.
I've accidentally faced with such problem myself and I was very happy when solved
it without "black magic" and any data loss.
So I wanted to write about it to the place where it's easy to find it (i.e FAQs).
I guess, I'm not the only one who faced with such problem.
> Add description of way to reset forgotten password into FAQs

- en-US/installation/install_from_source.md
The docs says `sqlite3` is an available build tags but the correct one is `sqlite`. It's correctly referenced further in the guide but this typo made me rebuild gogs quite a few times before I read the whole page.
> Fix typo in sqlite build tag

- en-US/intro/faqs.md
As a new user I was confused as to why I couldn't create or edit a Wiki for repos I was importing.. until I realized that Mirrored repos can't have their own Wiki.
> Add Wiki FAQ section

- en-US/installation/configuration_and_run.md
Rough draft of init script that starts gogs as a service on boot, as user 'git' from /home/git/ Golang installation.
(Gentoo/Funtoo)
> Example of running gogs as init service via openrc

- en-US/installation/install_from_binary.md
Hi @Unknwon , this PR makes some corrections to the "Installation from Binary" page, intended to make the first time experience even smoother.
Why? Having fought through the installation of a self-hosted GitLab in 2016, I was awestruck with the promising lightness of gogs. But then I almost almost tripped over the first sentence of the [Installation from binary](https://gogs.io/docs/installation/install_from_binary) page, which I (erroneously) read as: "the binary download _includes_ MySQL, PostgreSQL, etc.."
That sinking feeling _"Oh no, not another one packing everything and the kitchen sink!"_ turned out to be completely wrong. The opposite is true for gogs, and this PR intends to fix the issue by reorganising  the text a bit.
Many compliments on gogs! It gets everything _just right_.
> Improve smoothness of installation from binary

- en-US/installation/install_from_source.md
With Go 1.6.x:
$ go get -u github.com/gogs/gogs
. . .
package context: unrecognized import path "context" (import path does not begin with hostname)
> Requires Go 1.7

- de-DE/installation/install_from_source.md
The build tag name for sqlite3 support is just 'sqlite' and not 'sqlite3'.
Update the build instructions accordingly.
> Fix build tag name for sqlite3 in docs

- en-US/advanced/configuration_cheat_sheet.md
- zh-CN/advanced/configuration_cheat_sheet.md
Add dingtalk and QUEUE_LENGTH parameter of webhook in configuration file.
Changed files:
en-US/advanced/configuration_cheat_sheet.md
zh-CN/advanced/configuration_cheat_sheet.md
> Add dingtalk and QUEUE_LENGTH parameter of webhook in configuration file

- de-DE/installation/install_from_packages.md
- en-US/installation/install_from_packages.md
- fr-FR/installation/install_from_packages.md
- zh-CN/installation/install_from_packages.md
Since https://github.com/gogs/gogs/pull/5760, gogs/gogs is enabled in pkgr. This replaces pkgr/gogs links with gogs/gogs, and updates the supported distros.
I did the other translations too since the changes are theoretically straightforward, will revert those if you're not comfortable with that.
> Update packager.io information

- en-US/features/authentication.md
Closes #237 
With gratitude for an excellent and valuable open source project!
> Clean up the LDAP and FreeIPA documentation

- de-DE/intro/troubleshooting.md
- en-US/intro/troubleshooting.md
- fr-FR/intro/troubleshooting.md
From gogs/gogs#3877
Some french speaker should check the french translation as my french is a bit rusted. :D
> Added troubleshooting entry for passwords with special chars

- en-US/intro/faqs.md
@unknwon I added the instructions for reverse proxy through IIS (Windows Server).
If you might not accept this PR, I suggest putting all information regarding reverse proxy (Apache, Nginx, Caddy, IIS, etc) in a wiki page, instead of FAQ.
This configuration is in use in production by us.
> FAQ: Add IIS reverse proxy instructions

- de-DE/installation/configuration_and_run.md
- fr-FR/installation/configuration_and_run.md
The example in the French and German documentation now uses PASSWORD instead of PASSWD. Minor spelling corrections were applied to the German docs.
> Update documentation on db password

- de-DE/intro/faqs.md
The whole authorization scheme has been refactored in Apache 2.4 with RequireAll, RequireAny and RequireNone directives.
> allow deny is depreciated since apache24
